// File generated by FlutterFire CLI — replace by running:
//   dart pub global activate flutterfire_cli
//   flutterfire configure
//
// Until configured, placeholders below will prevent a real Firebase connection.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux — '
          'run flutterfire configure.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // TODO: Replace all values by running `flutterfire configure`
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeBYouKxv47RR2s4fmgZs3_QRiFga01rg',
    appId: '1:901927576776:web:3a8d0835845d0ecaf931fd',
    messagingSenderId: '901927576776',
    projectId: 'gmserp-ffc76',
    authDomain: 'gmserp-ffc76.firebaseapp.com',
    storageBucket: 'gmserp-ffc76.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMtetkIw2a2O1blzdzAhesuMjj1jsJgfs',
    appId: '1:901927576776:android:1350d8b3b8400b4df931fd',
    messagingSenderId: '901927576776',
    projectId: 'gmserp-ffc76',
    storageBucket: 'gmserp-ffc76.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwpoTTlFmMIoaLW3A0TBgOLYFAiBll6x8',
    appId: '1:901927576776:ios:68e7fcb7077349acf931fd',
    messagingSenderId: '901927576776',
    projectId: 'gmserp-ffc76',
    storageBucket: 'gmserp-ffc76.firebasestorage.app',
    iosBundleId: 'com.exampleGmserp.ios',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: 'YOUR_MACOS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
    iosBundleId: 'com.example.newGmserp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'YOUR_WINDOWS_API_KEY',
    appId: 'YOUR_WINDOWS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
  );
}
